//                                   _           _    __ _ _        //
//                                  | |         | |  / _(_) |       //
//    __ _  ___ _ __   ___ _ __ __ _| |_ ___  __| | | |_ _| | ___   //
//   / _` |/ _ \ '_ \ / _ \ '__/ _` | __/ _ \/ _` | |  _| | |/ _ \  //
//  | (_| |  __/ | | |  __/ | | (_| | ||  __/ (_| | | | | | |  __/  //
//   \__, |\___|_| |_|\___|_|  \__,_|\__\___|\__,_| |_| |_|_|\___|  //
//    __/ |                                                         //
//   |___/                                                          //
//                                                                  //
// Generated by:  libraries/chain_id/identify_chain.cpp             //
//                                                                  //
// Warning: This is a generated file, any changes made here will be //
// overwritten by the build process.  If you need to change what    //
// is generated here, you should use the CMake variable             //
// GRAPHENE_EGENESIS_JSON to specify an embedded genesis state.     //
//                                                                  //

/*
 * Copyright (c) 2015, Cryptonomex, Inc.
 * All rights reserved.
 *
 * This source code is provided for evaluation in private test networks only, until September 8, 2015. After this date, this license expires and
 * the code may not be used, modified or distributed for any purpose. Redistribution and use in source and binary forms, with or without modification,
 * are permitted until September 8, 2015, provided that the following conditions are met:
 *
 * 1. The code and/or derivative works are used only for private test networks consisting of no more than 10 P2P nodes.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <graphene/chain/protocol/types.hpp>
#include <graphene/egenesis/egenesis.hpp>

namespace graphene { namespace egenesis {

using namespace graphene::chain;

static const char genesis_json_array[187][40+1] =
{
"{\n  \"initial_timestamp\": \"2018-03-23T16:",
"40:00\",\n  \"max_core_supply\": \"5000000000",
"0000000\",\n  \"initial_parameters\": {\n    ",
"\"current_fees\": {\n      \"parameters\": [[",
"\n        0,{\n          \"fee\": 1000000\n  ",
"      }\n      ],[\n        1,{\n          ",
"\"basic_fee\": 1000000\n        }\n      ],[",
"\n        2,{\n          \"fee\": 1000000\n  ",
"      }\n      ],[\n        3,{\n          ",
"\"fee\": 100000000\n        }\n      ],[\n   ",
"     4,{\n          \"fee\": 1000000\n      ",
"  }\n      ],[\n        5,{\n          \"fee",
"\": 1000000\n        }\n      ],[\n        6",
",{\n          \"fee\": 1000000,\n          \"",
"price_per_kbyte\": 10\n        }\n      ],[",
"\n        7,{\n          \"fee\": 1000000,\n ",
"         \"price_per_kbyte\": 10\n        }",
"\n      ],[\n        8,{\n          \"fee\": ",
"1000000\n        }\n      ],[\n        9,{\n",
"          \"fee\": 1000000\n        }\n     ",
" ],[\n        10,{\n          \"fee\": 10000",
"00\n        }\n      ],[\n        11,{\n    ",
"      \"fee\": 1000000\n        }\n      ]\n ",
"     ],\n      \"scale\": 10000\n    },\n    ",
"\"block_interval\": 10,\n    \"maintenance_i",
"nterval\": 86400,\n    \"maintenance_skip_s",
"lots\": 3,\n    \"miner_proposal_review_per",
"iod\": 1209600,\n    \"freeze_transfers_aft",
"er_block\": 1000000,\n    \"maximum_transac",
"tion_size\": 4096,\n    \"maximum_block_siz",
"e\": 2048000,\n    \"maximum_time_until_exp",
"iration\": 86400,\n    \"maximum_proposal_l",
"ifetime\": 2419200,\n    \"maximum_asset_fe",
"ed_publishers\": 10,\n    \"maximum_miner_c",
"ount\": 11,\n    \"maximum_authority_member",
"ship\": 10,\n    \"cashback_vesting_period_",
"seconds\": 31536000,\n    \"cashback_vestin",
"g_threshold\": \"1000000000\",\n    \"max_pre",
"dicate_opcode\": 1,\n    \"max_authority_de",
"pth\": 2,\n    \"extensions\": []\n  },\n  \"in",
"itial_accounts\": [{\n      \"name\": \"CVA7X",
"sypoMUi82mWgiupq1JdEZaHZE1euUPy54Qci6C8j",
"afDsyUED\",\n      \"owner_key\": \"CVA7Xsypo",
"MUi82mWgiupq1JdEZaHZE1euUPy54Qci6C8jafDs",
"yUED\",\n      \"active_key\": \"CVA7XsypoMUi",
"82mWgiupq1JdEZaHZE1euUPy54Qci6C8jafDsyUE",
"D\"\n    },{\n      \"name\": \"CVA6k7NrLryUW7",
"pgpzyw43YexB12Djd5F7E5qJ7h6PhqW3GfeXp44\"",
",\n      \"owner_key\": \"CVA6k7NrLryUW7pgpz",
"yw43YexB12Djd5F7E5qJ7h6PhqW3GfeXp44\",\n  ",
"    \"active_key\": \"CVA6k7NrLryUW7pgpzyw4",
"3YexB12Djd5F7E5qJ7h6PhqW3GfeXp44\"\n    },",
"{\n      \"name\": \"CVA6XU8UQd2Lqc4Wv7hUxNp",
"oqpfYb2ZyD2eXvfNaY9iAybBMgAD1U\",\n      \"",
"owner_key\": \"CVA6XU8UQd2Lqc4Wv7hUxNpoqpf",
"Yb2ZyD2eXvfNaY9iAybBMgAD1U\",\n      \"acti",
"ve_key\": \"CVA6XU8UQd2Lqc4Wv7hUxNpoqpfYb2",
"ZyD2eXvfNaY9iAybBMgAD1U\"\n    },{\n      \"",
"name\": \"CVA6o8Bg9HZyx7q6hbz4Zjk5nhsZYhJx",
"sVcLxewL197g3tJSCR77k\",\n      \"owner_key",
"\": \"CVA6o8Bg9HZyx7q6hbz4Zjk5nhsZYhJxsVcL",
"xewL197g3tJSCR77k\",\n      \"active_key\": ",
"\"CVA6o8Bg9HZyx7q6hbz4Zjk5nhsZYhJxsVcLxew",
"L197g3tJSCR77k\"\n    },{\n      \"name\": \"C",
"VA7tVxiUQUsUqTyiSPAdo5Vm2Y9Kuc51RwcxJaVd",
"Dpt94AaBZQ3x\",\n      \"owner_key\": \"CVA7t",
"VxiUQUsUqTyiSPAdo5Vm2Y9Kuc51RwcxJaVdDpt9",
"4AaBZQ3x\",\n      \"active_key\": \"CVA7tVxi",
"UQUsUqTyiSPAdo5Vm2Y9Kuc51RwcxJaVdDpt94Aa",
"BZQ3x\"\n    },{\n      \"name\": \"CVA5wBkAp4",
"Xp11RWoJghfQegY84A1FB7DdgFShwi88EPUrd8U1",
"d5S\",\n      \"owner_key\": \"CVA5wBkAp4Xp11",
"RWoJghfQegY84A1FB7DdgFShwi88EPUrd8U1d5S\"",
",\n      \"active_key\": \"CVA5wBkAp4Xp11RWo",
"JghfQegY84A1FB7DdgFShwi88EPUrd8U1d5S\"\n  ",
"  },{\n      \"name\": \"CVA83QGnbrGvtJa8zm9",
"36Eyh58ogC6Vz6CXFDLLgqbMFapCzTcV4o\",\n   ",
"   \"owner_key\": \"CVA83QGnbrGvtJa8zm936Ey",
"h58ogC6Vz6CXFDLLgqbMFapCzTcV4o\",\n      \"",
"active_key\": \"CVA83QGnbrGvtJa8zm936Eyh58",
"ogC6Vz6CXFDLLgqbMFapCzTcV4o\"\n    },{\n   ",
"   \"name\": \"CVA8F5tvKn8uN8wuQJedg8y6KGuw",
"y38pvyeP69x17A1xbAiFbTJYz\",\n      \"owner",
"_key\": \"CVA8F5tvKn8uN8wuQJedg8y6KGuwy38p",
"vyeP69x17A1xbAiFbTJYz\",\n      \"active_ke",
"y\": \"CVA8F5tvKn8uN8wuQJedg8y6KGuwy38pvye",
"P69x17A1xbAiFbTJYz\"\n    },{\n      \"name\"",
": \"CVA5YE4tHiPf31opMf7UMbvi1cWuh4PFYVzKB",
"gmUiapM8qD5EytKN\",\n      \"owner_key\": \"C",
"VA5YE4tHiPf31opMf7UMbvi1cWuh4PFYVzKBgmUi",
"apM8qD5EytKN\",\n      \"active_key\": \"CVA5",
"YE4tHiPf31opMf7UMbvi1cWuh4PFYVzKBgmUiapM",
"8qD5EytKN\"\n    },{\n      \"name\": \"CVA8Hm",
"Sg3PhBxm5kRnJjp1FdWG66SDfMj3JfQMebDLaDDs",
"g4FPGSN\",\n      \"owner_key\": \"CVA8HmSg3P",
"hBxm5kRnJjp1FdWG66SDfMj3JfQMebDLaDDsg4FP",
"GSN\",\n      \"active_key\": \"CVA8HmSg3PhBx",
"m5kRnJjp1FdWG66SDfMj3JfQMebDLaDDsg4FPGSN",
"\"\n    },{\n      \"name\": \"CVA6qA9QuFyp5BF",
"cQD13fqv5V8eVfQL5z1rRoGDiddqFpTaNVbycG\",",
"\n      \"owner_key\": \"CVA6qA9QuFyp5BFcQD1",
"3fqv5V8eVfQL5z1rRoGDiddqFpTaNVbycG\",\n   ",
"   \"active_key\": \"CVA6qA9QuFyp5BFcQD13fq",
"v5V8eVfQL5z1rRoGDiddqFpTaNVbycG\"\n    },{",
"\n      \"name\": \"CVA7cGUNdApH4e958Nbj9WfE",
"wmcjLUsFk88tz6TJNGtNuJ6WXRiKz\",\n      \"o",
"wner_key\": \"CVA7cGUNdApH4e958Nbj9WfEwmcj",
"LUsFk88tz6TJNGtNuJ6WXRiKz\",\n      \"activ",
"e_key\": \"CVA7cGUNdApH4e958Nbj9WfEwmcjLUs",
"Fk88tz6TJNGtNuJ6WXRiKz\"\n    },{\n      \"n",
"ame\": \"CVA7VVS2JvqardqQ3hvGV8ANfHEQNn2Sx",
"C3RHKoHkGmzx8moRjFHy\",\n      \"owner_key\"",
": \"CVA7VVS2JvqardqQ3hvGV8ANfHEQNn2SxC3RH",
"KoHkGmzx8moRjFHy\",\n      \"active_key\": \"",
"CVA7VVS2JvqardqQ3hvGV8ANfHEQNn2SxC3RHKoH",
"kGmzx8moRjFHy\"\n    },{\n      \"name\": \"CV",
"A7rnCF7htZsQmChm8dMm8eL7hoJMoTEnJqQheEbH",
"KWBBKeZAibM\",\n      \"owner_key\": \"CVA7rn",
"CF7htZsQmChm8dMm8eL7hoJMoTEnJqQheEbHKWBB",
"KeZAibM\",\n      \"active_key\": \"CVA7rnCF7",
"htZsQmChm8dMm8eL7hoJMoTEnJqQheEbHKWBBKeZ",
"AibM\"\n    }\n  ],\n  \"initial_assets\": [\n ",
" ],\n  \"initial_active_miners\": 11,\n  \"in",
"itial_miner_candidates\": [{\n      \"owner",
"_name\": \"CVA7XsypoMUi82mWgiupq1JdEZaHZE1",
"euUPy54Qci6C8jafDsyUED\",\n      \"block_si",
"gning_key\": \"CVA8XDZkvMCE74En5iJpJYXCAAK",
"1Wj375KQkb1iJ5GFqWAX3ctggn\"\n    },{\n    ",
"  \"owner_name\": \"CVA6k7NrLryUW7pgpzyw43Y",
"exB12Djd5F7E5qJ7h6PhqW3GfeXp44\",\n      \"",
"block_signing_key\": \"CVA8XDZkvMCE74En5iJ",
"pJYXCAAK1Wj375KQkb1iJ5GFqWAX3ctggn\"\n    ",
"},{\n      \"owner_name\": \"CVA6XU8UQd2Lqc4",
"Wv7hUxNpoqpfYb2ZyD2eXvfNaY9iAybBMgAD1U\",",
"\n      \"block_signing_key\": \"CVA8XDZkvMC",
"E74En5iJpJYXCAAK1Wj375KQkb1iJ5GFqWAX3ctg",
"gn\"\n    },{\n      \"owner_name\": \"CVA6o8B",
"g9HZyx7q6hbz4Zjk5nhsZYhJxsVcLxewL197g3tJ",
"SCR77k\",\n      \"block_signing_key\": \"CVA",
"8XDZkvMCE74En5iJpJYXCAAK1Wj375KQkb1iJ5GF",
"qWAX3ctggn\"\n    },{\n      \"owner_name\": ",
"\"CVA7tVxiUQUsUqTyiSPAdo5Vm2Y9Kuc51RwcxJa",
"VdDpt94AaBZQ3x\",\n      \"block_signing_ke",
"y\": \"CVA8XDZkvMCE74En5iJpJYXCAAK1Wj375KQ",
"kb1iJ5GFqWAX3ctggn\"\n    },{\n      \"owner",
"_name\": \"CVA5wBkAp4Xp11RWoJghfQegY84A1FB",
"7DdgFShwi88EPUrd8U1d5S\",\n      \"block_si",
"gning_key\": \"CVA8XDZkvMCE74En5iJpJYXCAAK",
"1Wj375KQkb1iJ5GFqWAX3ctggn\"\n    },{\n    ",
"  \"owner_name\": \"CVA83QGnbrGvtJa8zm936Ey",
"h58ogC6Vz6CXFDLLgqbMFapCzTcV4o\",\n      \"",
"block_signing_key\": \"CVA8XDZkvMCE74En5iJ",
"pJYXCAAK1Wj375KQkb1iJ5GFqWAX3ctggn\"\n    ",
"},{\n      \"owner_name\": \"CVA8F5tvKn8uN8w",
"uQJedg8y6KGuwy38pvyeP69x17A1xbAiFbTJYz\",",
"\n      \"block_signing_key\": \"CVA8XDZkvMC",
"E74En5iJpJYXCAAK1Wj375KQkb1iJ5GFqWAX3ctg",
"gn\"\n    },{\n      \"owner_name\": \"CVA5YE4",
"tHiPf31opMf7UMbvi1cWuh4PFYVzKBgmUiapM8qD",
"5EytKN\",\n      \"block_signing_key\": \"CVA",
"8XDZkvMCE74En5iJpJYXCAAK1Wj375KQkb1iJ5GF",
"qWAX3ctggn\"\n    },{\n      \"owner_name\": ",
"\"CVA8HmSg3PhBxm5kRnJjp1FdWG66SDfMj3JfQMe",
"bDLaDDsg4FPGSN\",\n      \"block_signing_ke",
"y\": \"CVA8XDZkvMCE74En5iJpJYXCAAK1Wj375KQ",
"kb1iJ5GFqWAX3ctggn\"\n    },{\n      \"owner",
"_name\": \"CVA6qA9QuFyp5BFcQD13fqv5V8eVfQL",
"5z1rRoGDiddqFpTaNVbycG\",\n      \"block_si",
"gning_key\": \"CVA8XDZkvMCE74En5iJpJYXCAAK",
"1Wj375KQkb1iJ5GFqWAX3ctggn\"\n    }\n  ],\n ",
" \"initial_chain_id\": \"9a5e5be357cdfa2c48",
"dbe260f983a0109b52b9afdada705521cddad924",
"3522f7\",\n  \"initial_balances\": [{\n      ",
"\"owner\": \"CVA7cGUNdApH4e958Nbj9WfEwmcjLU",
"sFk88tz6TJNGtNuJ6WXRiKz\",\n      \"asset_s",
"ymbol\": \"CVA\",\n      \"amount\": \"15000000",
"000000000\"\n    },{\n      \"owner\": \"CVA7V",
"VS2JvqardqQ3hvGV8ANfHEQNn2SxC3RHKoHkGmzx",
"8moRjFHy\",\n      \"asset_symbol\": \"CVA\",\n",
"      \"amount\": \"6000000000000000\"\n    }",
",{\n      \"owner\": \"CVA7rnCF7htZsQmChm8dM",
"m8eL7hoJMoTEnJqQheEbHKWBBKeZAibM\",\n     ",
" \"asset_symbol\": \"CVA\",\n      \"amount\": ",
"\"4000000000000000\"\n    }\n  ],\n  \"immutab",
"le_parameters\": {\n    \"min_miner_count\":",
" 11,\n    \"num_special_accounts\": 0,\n    ",
"\"num_special_assets\": 0\n  }\n}\n"
};

chain_id_type get_egenesis_chain_id()
{
   return chain_id_type( "012456f7a81d5fc4263ab7b75219780dd83480e19ef4e13cd6f40ceb5beb7e2b" );
}

void compute_egenesis_json( std::string& result )
{
   result.reserve( 7470 );
   result.resize(0);
   for( size_t i=0; i<187-1; i++ )
   {
      result.append( genesis_json_array[i], 40 );
   }
   result.append( std::string( genesis_json_array[ 187-1 ] ) );
   return;
}

fc::sha256 get_egenesis_json_hash()
{
   return fc::sha256( "012456f7a81d5fc4263ab7b75219780dd83480e19ef4e13cd6f40ceb5beb7e2b" );
}

} }
