//                                   _           _    __ _ _        //
//                                  | |         | |  / _(_) |       //
//    __ _  ___ _ __   ___ _ __ __ _| |_ ___  __| | | |_ _| | ___   //
//   / _` |/ _ \ '_ \ / _ \ '__/ _` | __/ _ \/ _` | |  _| | |/ _ \  //
//  | (_| |  __/ | | |  __/ | | (_| | ||  __/ (_| | | | | | |  __/  //
//   \__, |\___|_| |_|\___|_|  \__,_|\__\___|\__,_| |_| |_|_|\___|  //
//    __/ |                                                         //
//   |___/                                                          //
//                                                                  //
// Generated by:  libraries/chain_id/identify_chain.cpp             //
//                                                                  //
// Warning: This is a generated file, any changes made here will be //
// overwritten by the build process.  If you need to change what    //
// is generated here, you should use the CMake variable             //
// GRAPHENE_EGENESIS_JSON to specify an embedded genesis state.     //
//                                                                  //

/*
 * Copyright (c) 2015, Cryptonomex, Inc.
 * All rights reserved.
 *
 * This source code is provided for evaluation in private test networks only, until September 8, 2015. After this date, this license expires and
 * the code may not be used, modified or distributed for any purpose. Redistribution and use in source and binary forms, with or without modification,
 * are permitted until September 8, 2015, provided that the following conditions are met:
 *
 * 1. The code and/or derivative works are used only for private test networks consisting of no more than 10 P2P nodes.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <graphene/chain/protocol/types.hpp>
#include <graphene/egenesis/egenesis.hpp>

namespace graphene { namespace egenesis {

using namespace graphene::chain;

static const char genesis_json_array[206][40+1] =
{
"{\n  \"initial_timestamp\": \"2018-11-11T11:",
"11:00\",\n  \"max_core_supply\": \"1000000000",
"00000000\",\n  \"initial_parameters\": {\n   ",
" \"current_fees\": {\n      \"parameters\": [",
"[\n        0,{\n          \"fee\": 1000000\n ",
"       }\n      ],[\n        1,{\n         ",
" \"basic_fee\": 1000000\n        }\n      ],",
"[\n        2,{\n          \"fee\": 1000000\n ",
"       }\n      ],[\n        3,{\n         ",
" \"fee\": 100000000\n        }\n      ],[\n  ",
"      4,{\n          \"fee\": 1000000\n     ",
"   }\n      ],[\n        5,{\n          \"fe",
"e\": 1000000\n        }\n      ],[\n        ",
"6,{\n          \"fee\": 1000000,\n          ",
"\"price_per_kbyte\": 10\n        }\n      ],",
"[\n        7,{\n          \"fee\": 1000000,\n",
"          \"price_per_kbyte\": 10\n        ",
"}\n      ],[\n        8,{\n          \"fee\":",
" 1000000\n        }\n      ],[\n        9,{",
"\n          \"fee\": 1000000\n        }\n    ",
"  ],[\n        10,{\n          \"fee\": 1000",
"000\n        }\n      ],[\n        11,{\n   ",
"       \"fee\": 1000000\n        }\n      ]\n",
"      ],\n      \"scale\": 10000\n    },\n   ",
" \"block_interval\": 30,\n    \"maintenance_",
"interval\": 86400,\n    \"maintenance_skip_",
"slots\": 3,\n    \"miner_proposal_review_pe",
"riod\": 1209600,\n    \"freeze_transfers_af",
"ter_block\": 100000000,\n    \"maximum_tran",
"saction_size\": 4096,\n    \"maximum_block_",
"size\": 8388608,\n    \"maximum_time_until_",
"expiration\": 86400,\n    \"maximum_proposa",
"l_lifetime\": 2419200,\n    \"maximum_asset",
"_feed_publishers\": 10,\n    \"maximum_mine",
"r_count\": 11,\n    \"maximum_authority_mem",
"bership\": 10,\n    \"cashback_vesting_peri",
"od_seconds\": 31536000,\n    \"cashback_ves",
"ting_threshold\": \"1000000000\",\n    \"max_",
"predicate_opcode\": 1,\n    \"max_authority",
"_depth\": 2,\n    \"extensions\": []\n  },\n  ",
"\"initial_accounts\": [{\n      \"name\": \"CV",
"A5jNq3xvd9g18WcXnGQoLiCnaTFWUNAwuPdt2fn5",
"yivZGNomGNF\",\n      \"owner_key\": \"CVA5jN",
"q3xvd9g18WcXnGQoLiCnaTFWUNAwuPdt2fn5yivZ",
"GNomGNF\",\n      \"active_key\": \"CVA5jNq3x",
"vd9g18WcXnGQoLiCnaTFWUNAwuPdt2fn5yivZGNo",
"mGNF\"\n    },{\n      \"name\": \"CVA6dxZCkFq",
"MtGKMobDH2Uhmis3wZNKHcHDLQphLrLedEPU8QZM",
"zM\",\n      \"owner_key\": \"CVA6dxZCkFqMtGK",
"MobDH2Uhmis3wZNKHcHDLQphLrLedEPU8QZMzM\",",
"\n      \"active_key\": \"CVA6dxZCkFqMtGKMob",
"DH2Uhmis3wZNKHcHDLQphLrLedEPU8QZMzM\"\n   ",
" },{\n      \"name\": \"CVA76WgTTLUJwF9uYuk2",
"ENzZ2pkUzjdHY6CAnehVmogpdR4NRSXbj\",\n    ",
"  \"owner_key\": \"CVA76WgTTLUJwF9uYuk2ENzZ",
"2pkUzjdHY6CAnehVmogpdR4NRSXbj\",\n      \"a",
"ctive_key\": \"CVA76WgTTLUJwF9uYuk2ENzZ2pk",
"UzjdHY6CAnehVmogpdR4NRSXbj\"\n    },{\n    ",
"  \"name\": \"CVA6o4Bgp2X88aMeGHEbsvco4jDJB",
"JHeQn9kKJMeLPL15nDL88NrS\",\n      \"owner_",
"key\": \"CVA6o4Bgp2X88aMeGHEbsvco4jDJBJHeQ",
"n9kKJMeLPL15nDL88NrS\",\n      \"active_key",
"\": \"CVA6o4Bgp2X88aMeGHEbsvco4jDJBJHeQn9k",
"KJMeLPL15nDL88NrS\"\n    },{\n      \"name\":",
" \"CVA7DDucAydWLuUQCXJxf5BfNg6kEn1a7s8Uos",
"nVrRGLfnuZQs9c7\",\n      \"owner_key\": \"CV",
"A7DDucAydWLuUQCXJxf5BfNg6kEn1a7s8UosnVrR",
"GLfnuZQs9c7\",\n      \"active_key\": \"CVA7D",
"DucAydWLuUQCXJxf5BfNg6kEn1a7s8UosnVrRGLf",
"nuZQs9c7\"\n    },{\n      \"name\": \"CVA55WF",
"R6xNgoBiJ9qYk8KW9cSWzBh7JyJ2SKPMBrbiEtVh",
"rsJ4z4\",\n      \"owner_key\": \"CVA55WFR6xN",
"goBiJ9qYk8KW9cSWzBh7JyJ2SKPMBrbiEtVhrsJ4",
"z4\",\n      \"active_key\": \"CVA55WFR6xNgoB",
"iJ9qYk8KW9cSWzBh7JyJ2SKPMBrbiEtVhrsJ4z4\"",
"\n    },{\n      \"name\": \"CVA6tinXUqzdCTQn",
"tzBYdHgPGBoxK5159b7jN1GbcrTfzyf9wVe8D\",\n",
"      \"owner_key\": \"CVA6tinXUqzdCTQntzBY",
"dHgPGBoxK5159b7jN1GbcrTfzyf9wVe8D\",\n    ",
"  \"active_key\": \"CVA6tinXUqzdCTQntzBYdHg",
"PGBoxK5159b7jN1GbcrTfzyf9wVe8D\"\n    },{\n",
"      \"name\": \"CVA7CQbtHU5ufEtRjHBJTbRWS",
"7hbYQ2B5y4YvRndcjAq1TqpbzFdg\",\n      \"ow",
"ner_key\": \"CVA7CQbtHU5ufEtRjHBJTbRWS7hbY",
"Q2B5y4YvRndcjAq1TqpbzFdg\",\n      \"active",
"_key\": \"CVA7CQbtHU5ufEtRjHBJTbRWS7hbYQ2B",
"5y4YvRndcjAq1TqpbzFdg\"\n    },{\n      \"na",
"me\": \"CVA8kX1UDGWHWLNSV7DYUwi5vFUEizCiHJ",
"mKB2y8e8Yhp2cSozjm2\",\n      \"owner_key\":",
" \"CVA8kX1UDGWHWLNSV7DYUwi5vFUEizCiHJmKB2",
"y8e8Yhp2cSozjm2\",\n      \"active_key\": \"C",
"VA8kX1UDGWHWLNSV7DYUwi5vFUEizCiHJmKB2y8e",
"8Yhp2cSozjm2\"\n    },{\n      \"name\": \"CVA",
"8Uwk9VKYQkuzwRK3nhtYmGjRPzBsxwc6aCkkKQpX",
"oMhMnYKjDc\",\n      \"owner_key\": \"CVA8Uwk",
"9VKYQkuzwRK3nhtYmGjRPzBsxwc6aCkkKQpXoMhM",
"nYKjDc\",\n      \"active_key\": \"CVA8Uwk9VK",
"YQkuzwRK3nhtYmGjRPzBsxwc6aCkkKQpXoMhMnYK",
"jDc\"\n    },{\n      \"name\": \"CVA7miDAXtUS",
"MEJpZLgEjYQyVRDe27hCqYUDFTWFVbgDRAwesPTy",
"u\",\n      \"owner_key\": \"CVA7miDAXtUSMEJp",
"ZLgEjYQyVRDe27hCqYUDFTWFVbgDRAwesPTyu\",\n",
"      \"active_key\": \"CVA7miDAXtUSMEJpZLg",
"EjYQyVRDe27hCqYUDFTWFVbgDRAwesPTyu\"\n    ",
"},{\n      \"name\": \"CVA8f4eMzscbG1pSTBjxy",
"1n5YdYtfo6tN5KxXGWrDzBctCti155C6\",\n     ",
" \"owner_key\": \"CVA8f4eMzscbG1pSTBjxy1n5Y",
"dYtfo6tN5KxXGWrDzBctCti155C6\",\n      \"ac",
"tive_key\": \"CVA8f4eMzscbG1pSTBjxy1n5YdYt",
"fo6tN5KxXGWrDzBctCti155C6\"\n    },{\n     ",
" \"name\": \"CVA5Ci5J2h4LK4LfnyiNPvMBqHYcwU",
"KUSGCeYiXqfivVrdue1a6yq\",\n      \"owner_k",
"ey\": \"CVA5Ci5J2h4LK4LfnyiNPvMBqHYcwUKUSG",
"CeYiXqfivVrdue1a6yq\",\n      \"active_key\"",
": \"CVA5Ci5J2h4LK4LfnyiNPvMBqHYcwUKUSGCeY",
"iXqfivVrdue1a6yq\"\n    },{\n      \"name\": ",
"\"CVA5T7xzfBKgBarDF3msyQYYZzCNgDmhf4QtkZ1",
"vHSbL7XuFFb6Hn\",\n      \"owner_key\": \"CVA",
"5T7xzfBKgBarDF3msyQYYZzCNgDmhf4QtkZ1vHSb",
"L7XuFFb6Hn\",\n      \"active_key\": \"CVA5T7",
"xzfBKgBarDF3msyQYYZzCNgDmhf4QtkZ1vHSbL7X",
"uFFb6Hn\"\n    },{\n      \"name\": \"CVA7oQ8T",
"Kw3NqopYVfUEeQ8mZgNYhfpYNGTNcpz7aQ5ixEtt",
"TtyuN\",\n      \"owner_key\": \"CVA7oQ8TKw3N",
"qopYVfUEeQ8mZgNYhfpYNGTNcpz7aQ5ixEttTtyu",
"N\",\n      \"active_key\": \"CVA7oQ8TKw3Nqop",
"YVfUEeQ8mZgNYhfpYNGTNcpz7aQ5ixEttTtyuN\"\n",
"    },{\n       \"name\": \"CVA6hPtKDvYHNSXD",
"6oR3fTHoB7oHQiEh4u19kWQF7v3PqbfDdkHck\",\n",
"       \"owner_key\": \"CVA6hPtKDvYHNSXD6oR",
"3fTHoB7oHQiEh4u19kWQF7v3PqbfDdkHck\",\n   ",
"    \"active_key\": \"CVA6hPtKDvYHNSXD6oR3f",
"THoB7oHQiEh4u19kWQF7v3PqbfDdkHck\"\n    }\n",
"  ],\n  \"initial_assets\": [\n  ],\n  \"initi",
"al_active_miners\": 11,\n  \"initial_miner_",
"candidates\": [{\n      \"owner_name\": \"CVA",
"5jNq3xvd9g18WcXnGQoLiCnaTFWUNAwuPdt2fn5y",
"ivZGNomGNF\",\n      \"block_signing_key\": ",
"\"CVA5jNq3xvd9g18WcXnGQoLiCnaTFWUNAwuPdt2",
"fn5yivZGNomGNF\"\n    },{\n      \"owner_nam",
"e\": \"CVA6dxZCkFqMtGKMobDH2Uhmis3wZNKHcHD",
"LQphLrLedEPU8QZMzM\",\n      \"block_signin",
"g_key\": \"CVA6dxZCkFqMtGKMobDH2Uhmis3wZNK",
"HcHDLQphLrLedEPU8QZMzM\"\n    },{\n      \"o",
"wner_name\": \"CVA76WgTTLUJwF9uYuk2ENzZ2pk",
"UzjdHY6CAnehVmogpdR4NRSXbj\",\n      \"bloc",
"k_signing_key\": \"CVA76WgTTLUJwF9uYuk2ENz",
"Z2pkUzjdHY6CAnehVmogpdR4NRSXbj\"\n    },{\n",
"      \"owner_name\": \"CVA6o4Bgp2X88aMeGHE",
"bsvco4jDJBJHeQn9kKJMeLPL15nDL88NrS\",\n   ",
"   \"block_signing_key\": \"CVA6o4Bgp2X88aM",
"eGHEbsvco4jDJBJHeQn9kKJMeLPL15nDL88NrS\"\n",
"    },{\n      \"owner_name\": \"CVA7DDucAyd",
"WLuUQCXJxf5BfNg6kEn1a7s8UosnVrRGLfnuZQs9",
"c7\",\n      \"block_signing_key\": \"CVA7DDu",
"cAydWLuUQCXJxf5BfNg6kEn1a7s8UosnVrRGLfnu",
"ZQs9c7\"\n    },{\n      \"owner_name\": \"CVA",
"55WFR6xNgoBiJ9qYk8KW9cSWzBh7JyJ2SKPMBrbi",
"EtVhrsJ4z4\",\n      \"block_signing_key\": ",
"\"CVA55WFR6xNgoBiJ9qYk8KW9cSWzBh7JyJ2SKPM",
"BrbiEtVhrsJ4z4\"\n    },{\n      \"owner_nam",
"e\": \"CVA6tinXUqzdCTQntzBYdHgPGBoxK5159b7",
"jN1GbcrTfzyf9wVe8D\",\n      \"block_signin",
"g_key\": \"CVA6tinXUqzdCTQntzBYdHgPGBoxK51",
"59b7jN1GbcrTfzyf9wVe8D\"\n    },{\n      \"o",
"wner_name\": \"CVA7CQbtHU5ufEtRjHBJTbRWS7h",
"bYQ2B5y4YvRndcjAq1TqpbzFdg\",\n      \"bloc",
"k_signing_key\": \"CVA7CQbtHU5ufEtRjHBJTbR",
"WS7hbYQ2B5y4YvRndcjAq1TqpbzFdg\"\n    },{\n",
"      \"owner_name\": \"CVA8kX1UDGWHWLNSV7D",
"YUwi5vFUEizCiHJmKB2y8e8Yhp2cSozjm2\",\n   ",
"   \"block_signing_key\": \"CVA8kX1UDGWHWLN",
"SV7DYUwi5vFUEizCiHJmKB2y8e8Yhp2cSozjm2\"\n",
"    },{\n      \"owner_name\": \"CVA8Uwk9VKY",
"QkuzwRK3nhtYmGjRPzBsxwc6aCkkKQpXoMhMnYKj",
"Dc\",\n      \"block_signing_key\": \"CVA8Uwk",
"9VKYQkuzwRK3nhtYmGjRPzBsxwc6aCkkKQpXoMhM",
"nYKjDc\"\n    },{\n      \"owner_name\": \"CVA",
"7miDAXtUSMEJpZLgEjYQyVRDe27hCqYUDFTWFVbg",
"DRAwesPTyu\",\n      \"block_signing_key\": ",
"\"CVA7miDAXtUSMEJpZLgEjYQyVRDe27hCqYUDFTW",
"FVbgDRAwesPTyu\"\n    }\n  ],\n  \"initial_ch",
"ain_id\": \"107e3efd3df89902907f5385026d68",
"237721c2d203e14a506dae7d9ec50675a9\",\n  \"",
"initial_balances\": [{\n      \"owner\": \"CV",
"A8f4eMzscbG1pSTBjxy1n5YdYtfo6tN5KxXGWrDz",
"BctCti155C6\",\n      \"asset_symbol\": \"CVA",
"\",\n      \"amount\": \"65000000000000000\"\n ",
"   },{\n      \"owner\": \"CVA5Ci5J2h4LK4Lfn",
"yiNPvMBqHYcwUKUSGCeYiXqfivVrdue1a6yq\",\n ",
"     \"asset_symbol\": \"CVA\",\n      \"amoun",
"t\": \"7000000000000000\"\n    },{\n      \"ow",
"ner\": \"CVA5T7xzfBKgBarDF3msyQYYZzCNgDmhf",
"4QtkZ1vHSbL7XuFFb6Hn\",\n      \"asset_symb",
"ol\": \"CVA\",\n      \"amount\": \"50000000000",
"00000\"\n    },{\n      \"owner\": \"CVA7oQ8TK",
"w3NqopYVfUEeQ8mZgNYhfpYNGTNcpz7aQ5ixEttT",
"tyuN\",\n      \"asset_symbol\": \"CVA\",\n    ",
"  \"amount\": \"3000000000000000\"\n    },{\n ",
"     \"owner\": \"CVA6hPtKDvYHNSXD6oR3fTHoB",
"7oHQiEh4u19kWQF7v3PqbfDdkHck\",\n      \"as",
"set_symbol\": \"CVA\",\n      \"amount\": \"0\"\n",
"    }\n  ],\n  \"immutable_parameters\": {\n ",
"   \"min_miner_count\": 11,\n    \"num_speci",
"al_accounts\": 0,\n    \"num_special_assets",
"\": 0\n  }\n}\n"
};

chain_id_type get_egenesis_chain_id()
{
   return chain_id_type( "b617f2e6d46bc04d06fb480bbda309699cccaf8dd5c6e5d12ed0af9723cf3129" );
}

void compute_egenesis_json( std::string& result )
{
   result.reserve( 8211 );
   result.resize(0);
   for( size_t i=0; i<206-1; i++ )
   {
      result.append( genesis_json_array[i], 40 );
   }
   result.append( std::string( genesis_json_array[ 206-1 ] ) );
   return;
}

fc::sha256 get_egenesis_json_hash()
{
   return fc::sha256( "b617f2e6d46bc04d06fb480bbda309699cccaf8dd5c6e5d12ed0af9723cf3129" );
}

} }
